#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Fri Apr 11 11:58:53 2014

import wx
import Gnuplot
import math

ID_SLIDER_1 = wx.NewId()
ID_SLIDER_2 = wx.NewId()
ID_SLIDER_3 = wx.NewId()
ID_SLIDER_4 = wx.NewId()
ID_SLIDER_5 = wx.NewId()
ID_SLIDER_6 = wx.NewId()
ID_SLIDER_7 = wx.NewId()
ID_SLIDER_8 = wx.NewId()
ID_SLIDER_9 = wx.NewId()
ID_SLIDER_10 = wx.NewId()
ID_SLIDER_11 = wx.NewId()
ID_SLIDER_12 = wx.NewId()
ID_SLIDER_13 = wx.NewId()


# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.slider_1 = wx.Slider(self, ID_SLIDER_1, 6, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_2 = wx.Slider(self, ID_SLIDER_2, 1, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_3 = wx.Slider(self, ID_SLIDER_3, 3, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_4 = wx.Slider(self, ID_SLIDER_4, 4, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_5 = wx.Slider(self, ID_SLIDER_5, 4, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_6 = wx.Slider(self, ID_SLIDER_6, 6, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_7 = wx.Slider(self, ID_SLIDER_7, 6, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
	self.slider_8 = wx.Slider(self, ID_SLIDER_8, 8, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
	self.slider_9 = wx.Slider(self, ID_SLIDER_9, 3, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
	self.slider_10 = wx.Slider(self, ID_SLIDER_10, 12, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
	self.slider_11 = wx.Slider(self, ID_SLIDER_11, 4, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
	self.slider_12 = wx.Slider(self, ID_SLIDER_12, 6, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)
        self.slider_13 = wx.Slider(self, ID_SLIDER_13, 10, 0, 100, style=wx.SL_VERTICAL | wx.SL_LABELS)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

	wx.EVT_SLIDER(self, ID_SLIDER_1, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_2, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_3, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_4, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_5, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_6, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_7, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_8, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_9, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_10, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_11, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_12, self.update)
        wx.EVT_SLIDER(self, ID_SLIDER_13, self.update)

	self.g = Gnuplot.Gnuplot()
	self.g('set xrange [-30:30]')
	self.g('set yrange [-30:30]')
	self.g('set style data dots')
	# do first plot
        self.update(self)

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((240, 240))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.GridSizer(1, 13, 0, 0)
        grid_sizer_1.Add(self.slider_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_2, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_3, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_4, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_5, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_6, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_7, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_8, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_9, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_10, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_11, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_12, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.slider_13, 0, wx.EXPAND, 0)

        self.SetSizer(grid_sizer_1)
        self.Layout()
        # end wxGlade

    def update(self,event):
	# put your function here!
	xyz = []
	t = 0.5 * 2 * math.pi
	a = self.slider_1.GetValue() 
	b = self.slider_2.GetValue() 
	c = self.slider_3.GetValue()
	d = self.slider_4.GetValue() 
	e = self.slider_5.GetValue() 
	f = self.slider_6.GetValue() 
	g = self.slider_7.GetValue() 
	h = self.slider_8.GetValue() 
	i = self.slider_9.GetValue() 
	j = self.slider_10.GetValue() 
	k = self.slider_11.GetValue() 
	l = self.slider_12.GetValue()
	m = self.slider_13.GetValue()
	while (t < 2.5 * 2 * math.pi):
	    x = a*math.sin(b*t)*(math.exp(math.cos(t))-c*math.cos(d*t)-pow(math.sin(t/e),f))
	    y = a*math.cos(b*t)*(math.exp(math.cos(t))-c*math.cos(d*t)-pow(math.sin(t/e),f))
            z = g*math.sin(h*t)*(math.exp(math.cos(t))-i*math.cos(j*t)-pow(math.sin(t/k),l))
	    xyz.append([x,y,z])
	    t += 4*math.pi / 5000.
        self.g.splot(xyz)

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
